version: "3.8"
services:

  # 🧩 Jenkins - CI/CD Automation Server
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    restart: always
    ports:
      - "8080:8080"   # Web UI
      - "50000:50000" # Agent communication port (JNLP)
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - devops_net

  # 🧩 SonarQube - Static Code Analysis
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - jenkins
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - devops_net

  # 🧩 Nexus - Artifact Repository
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    networks:
      - devops_net

# =============================
#   Networks & Volumes
# =============================
networks:
  devops_net:
    driver: bridge

volumes:
  jenkins_data:
  sonarqube_data:
  sonarqube_extensions:
  nexus_data:
